version: '3.8'
services:
  giasu:
    build: .
    image: talja123/giasu:latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app:ro
